### ISSUE TITLE
Crashes on Startup

### ISSUE THREAD

**Issue by bigmaxine** [PvPHubLLC/Blossom#1]
[20:19:45 INFO]: [Blossom] Enabling Blossom v1.0
[20:19:45 ERROR]: Error occurred while enabling Blossom v1.0 (Is it up to date?)
java.lang.IllegalArgumentException: The embedded resource 'config.yml' cannot be found in plugins/blossom-backend-dev-all.jar
	at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:207) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.saveDefaultConfig(JavaPlugin.java:194) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at co.pvphub.blossom.backend.BlossomBackend.onEnable(BlossomBackend.kt:16) ~[blossom-backend-dev-all.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.19.4.jar:git-Purpur-1967]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.4.jar:git-Purpur-1967]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:569) ~[purpur-1.19.4.jar:git-Purpur-1967]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:480) ~[purpur-1.19.4.jar:git-Purpur-1967]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:643) ~[purpur-1.19.4.jar:git-Purpur-1967]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442) ~[purpur-1.19.4.jar:git-Purpur-1967]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:344) ~[purpur-1.19.4.jar:git-Purpur-1967]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1967]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1967]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[20:19:45 INFO]: [Blossom] Disabling Blossom v1.0

**Comment by xyzaurora** [comment]
I see the issue here. Fixing with a release now.
